"""
Configuration package.
"""
from .settings import (
    LIVE_TRADING_ENABLED,
    BYBIT_REST_API_URL,
    BYBIT_SPOT_WS_URL,
    DEFAULT_MONITORED_MARKETS,
    STALE_DATA_TIMEOUT_SECONDS,
    MAX_ACCEPTABLE_LATENCY_MS,
    PAPER_TRADING_INITIAL_BALANCE,
)

__all__ = [
    "LIVE_TRADING_ENABLED",
    "BYBIT_REST_API_URL",
    "BYBIT_SPOT_WS_URL",
    "DEFAULT_MONITORED_MARKETS",
    "STALE_DATA_TIMEOUT_SECONDS",
    "MAX_ACCEPTABLE_LATENCY_MS",
    "PAPER_TRADING_INITIAL_BALANCE",
]
